### ISSUE TITLE
When the vite_ruby document is translated into Chinese using Google Chrome's translation tool, the text style in the navigation bar is abnormal.

### ISSUE THREAD

**Issue by declanchiu** [ElMassimo/vitepress-theme#1]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x ] I have tried upgrading by running `bundle update vite_ruby`.
- [x ] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

_Provide a clear and concise description of what the bug is._

![image](https://user-images.githubusercontent.com/55419399/186107282-ca4338df-df9b-40f2-bdb7-74dffc6b0886.png)

**Comment by ElMassimo** [comment]
Thanks for reporting! 

Would you check if the same occurs when translating [this documentation](https://vuejs.org/)?

**Comment by declanchiu** [comment]
@ElMassimo  

Oh, I got your point, you think it's vitepress that's causing the problem, but I'm sorry I didn't find the same problem at vuejs.org. 

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/55419399/186162617-3ce91fd4-99fe-4431-bd83-2622c832ea7a.png">

**Comment by ElMassimo** [comment]
Gotcha, seems like this was fixed here:

- https://github.com/vuejs/theme/issues/56

Pull requests to apply this fix are welcome!

**Comment by ambodu** [comment]
https://github.com/vuejs/theme/issues/56 only solved the bug in vuejs/theme so that the problem occurs in vitepress. just wait for them merge this pr and release a new version.😃

**Comment by declanchiu** [comment]
@dboooo  OK ! Thanks guys.   😊

**Comment by brc-dd** [comment]
@dboooo This is a totally custom theme. Even if we fix this in VitePress' default theme, it still would need to fixed here separately.

**Comment by ambodu** [comment]
@brc-dd oooo I totally didn't notice that, we should fixed it spearately!!

**Comment by declanchiu** [comment]
> @brc-ddoooo 我完全没有注意到，我们应该单独修复它！

So you're going to submit a pr to fix it?

**Comment by ambodu** [comment]
@PlayGuitar-CoderQ ok :)

**Comment by ElMassimo** [comment]
Fixed by #2 and deployed, thanks! 😃
